upstream api_gateway {
  server api-gateway:8080;
}
upstream auth_api {
  server auth-api:8081;
}
server {
  listen 80;
  server_name _;
  add_header X-Frame-Options "DENY" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  add_header X-XSS-Protection "1; mode=block" always;
  location /auth/ {
    rewrite ^/auth/?(.*)$ / break;
    proxy_pass http://auth_api;
    proxy_http_version 1.1;
    proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
    proxy_set_header X-Real-IP ;
    proxy_set_header X-Forwarded-For ;
    proxy_set_header X-Forwarded-Proto ;
  }
  location = /auth {
    proxy_pass http://auth_api/;
    proxy_http_version 1.1;
    proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
    proxy_set_header X-Real-IP ;
    proxy_set_header X-Forwarded-For ;
    proxy_set_header X-Forwarded-Proto ;
  }
  location / {
    proxy_pass http://api_gateway;
    proxy_http_version 1.1;
    proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
    proxy_set_header X-Real-IP ;
    proxy_set_header X-Forwarded-For ;
    proxy_set_header X-Forwarded-Proto ;
  }
}
