export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/token/refresh',
    meFallback: '/auth/me',
  },
  identity: {
    me: '/auth/me',
    contexts: '/me/contexts',
    switchContext: '/me/context/switch',
  },
  uiTheme: {
    platform: '/ui/theme/platform',
    effective: '/ui/theme/effective',
    list: '/ui/theme',
    create: '/ui/theme',
    update: (id: string) => `/ui/theme/${id}`,
    logo: (id: string) => `/ui/theme/${id}/logo`,
  },
  doctorRegistry: {
    search: '/doctors/search',
    profile: (doctorId: string) => `/doctors/${doctorId}`,
  },
  records: {
    me: '/records/me',
    byNin: (nin: string) => `/records/${nin}`,
    addSymptom: '/records/me/symptoms',
  },
  emergency: {
    inventorySearch: '/emergency/inventory/search',
    requests: '/emergency/requests',
  },
  taskforce: {
    dashboard: '/cases',
    complaints: '/cases',
    complaintById: (id: string) => `/cases/${id}`,
    assignComplaint: (id: string) => `/cases/${id}/assign`,
    escalateComplaint: (id: string) => `/cases/${id}/escalate`,
    convertComplaintToCase: (id: string) => `/cases/${id}/convert`,
    cases: '/cases',
    caseById: (id: string) => `/cases/${id}`,
    caseNotes: (id: string) => `/cases/${id}/notes`,
    assignCase: (id: string) => `/cases/${id}/assign`,
    escalateCase: (id: string) => `/cases/${id}/escalate`,
  },
  governance: {
    auditEvents: '/audit/events',
    oversight: '/cases',
  },
  provider: {
    patientSearch: '/profile/search',
    patientProfileByNin: (nin: string) => `/profile/by-nin/${nin}`,
    encountersByNin: (nin: string) => `/encounters/${nin}`,
    encounterById: (id: string) => `/encounters/id/${id}`,
    createEncounterByNin: (nin: string) => `/encounters/${nin}`,
    updateEncounterById: (id: string) => `/encounters/id/${id}`,
    finalizeEncounterById: (id: string) => `/encounters/id/${id}/finalize`,
    labsByNin: (nin: string) => `/labs/${nin}/results`,
    labById: (id: string) => `/labs/results/id/${id}`,
    createLabByNin: (nin: string) => `/labs/${nin}/results`,
    updateLabById: (id: string) => `/labs/results/id/${id}`,
    completeLabById: (id: string) => `/labs/results/id/${id}/complete`,
    pharmacyByNin: (nin: string) => `/pharmacy/${nin}/dispenses`,
    pharmacyById: (id: string) => `/pharmacy/dispenses/id/${id}`,
    createPharmacyByNin: (nin: string) => `/pharmacy/${nin}/dispenses`,
    updatePharmacyById: (id: string) => `/pharmacy/dispenses/id/${id}`,
    dispensePharmacyById: (id: string) => `/pharmacy/dispenses/id/${id}/dispense`,
  },
};
