export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/token/refresh',
    passwordSet: '/auth/password/set',
    meFallback: '/auth/me',
    userSearch: '/auth/users/search',
    ninLookup: (nin: string) => `/nin/${nin}`,
  },
  identity: {
    me: '/auth/me',
    contexts: '/auth/me',
    switchContext: '/auth/context/switch',
  },
  uiTheme: {
    platform: '/ui/theme/platform',
    effective: '/ui/theme/effective',
    list: '/ui/theme',
    create: '/ui/theme',
    update: (id: string) => `/ui/theme/${id}`,
    logo: (id: string) => `/ui/theme/${id}/logo`,
  },
  doctorRegistry: {
    search: '/doctors/search',
    profile: (doctorId: string) => `/doctors/${doctorId}`,
  },
  records: {
    me: '/records/me',
    byNin: (nin: string) => `/records/${nin}`,
    addSymptom: '/records/me/symptoms',
  },
  emergency: {
    inventorySearch: '/emergency/inventory/search',
    requests: '/emergency/requests',
    caseById: (id: string) => `/emergency/requests/${id}`,
    caseResponses: (id: string) => `/emergency/requests/${id}/responses`,
    caseRoom: (id: string) => `/emergency/requests/${id}/room`,
    roomMessages: (roomId: string) => `/emergency/rooms/${roomId}/messages`,
    updateStatus: (id: string) => `/emergency/requests/${id}/status`,
  },
  notifications: {
    list: '/audit/events',
    read: () => '/audit/events',
    readAll: '/audit/events',
  },
  alerts: {
    list: '/alerts',
  },
  institution: {
    dashboard: '/institution/dashboard',
  },
  system: {
    activity: '/system/activity',
    configuration: '/system/configuration',
    health: '/system/health',
    monitoring: '/system/monitoring',
    incidents: '/system/incidents',
    devTools: '/system/dev-tools',
  },
  integrations: {
    list: '/integrations',
    byId: (id: string) => `/integrations/${id}`,
    test: (id: string) => `/integrations/${id}/test`,
    disable: (id: string) => `/integrations/${id}/disable`,
    apiKeys: '/integrations/api-keys',
    apiKeyById: (id: string) => `/integrations/api-keys/${id}`,
    rotateApiKey: (id: string) => `/integrations/api-keys/${id}/rotate`,
    revokeApiKey: (id: string) => `/integrations/api-keys/${id}/revoke`,
    syncEvents: '/integrations/sync',
  },
  analytics: {
    dashboard: '/analytics/dashboard',
    metrics: '/analytics/metrics',
  },
  reports: {
    list: '/reports',
    byId: (reportId: string) => `/reports/${reportId}`,
    generate: (reportId: string) => `/reports/${reportId}/generate`,
    download: (reportId: string) => `/reports/${reportId}/download`,
  },
  compliance: {
    dataQuality: '/compliance/data-quality',
    summary: '/compliance/summary',
  },
  admin: {
    institutions: '/admin/institutions',
    institutionById: (institutionId: string) => `/admin/institutions/${institutionId}`,
    settings: '/admin/system-settings',
  },
  org: {
    list: '/orgs',
    deleted: '/orgs/deleted',
    search: '/orgs/search',
    byId: (orgId: string) => `/orgs/${orgId}`,
    approval: (orgId: string) => `/orgs/${orgId}/approval`,
    deletionRequest: (orgId: string) => `/orgs/${orgId}/deletion/request`,
    deletionReview: (orgId: string) => `/orgs/${orgId}/deletion/review`,
    restore: (orgId: string) => `/orgs/${orgId}/restore`,
    uploadFile: (orgId: string) => `/orgs/${orgId}/files/upload`,
    hierarchy: (orgId: string) => `/orgs/${orgId}/hierarchy`,
    globalInstitutions: '/institutions',
    globalInstitutionById: (institutionId: string) => `/institutions/${institutionId}`,
    globalBranches: '/branches',
    globalBranchById: (branchId: string) => `/branches/${branchId}`,
    institutions: (orgId: string) => `/orgs/${orgId}/institutions`,
    institutionById: (orgId: string, institutionId: string) => `/orgs/${orgId}/institutions/${institutionId}`,
    institutionBranches: (orgId: string, institutionId: string) => `/orgs/${orgId}/institutions/${institutionId}/branches`,
    institutionBranchById: (orgId: string, institutionId: string, branchId: string) =>
      `/orgs/${orgId}/institutions/${institutionId}/branches/${branchId}`,
    branches: (orgId: string) => `/orgs/${orgId}/branches`,
    branchById: (orgId: string, branchId: string) => `/orgs/${orgId}/branches/${branchId}`,
    members: (orgId: string) => `/orgs/${orgId}/members`,
    memberById: (orgId: string, memberId: string) => `/orgs/${orgId}/members/${memberId}`,
    memberBranchAssignments: (orgId: string, memberId: string) => `/orgs/${orgId}/members/${memberId}/branches`,
    memberBranchAssignmentById: (orgId: string, memberId: string, assignmentId: string) =>
      `/orgs/${orgId}/members/${memberId}/branches/${assignmentId}`,
  },
  rbac: {
    appPermissions: '/rbac/app/permissions',
    appRoles: '/rbac/app/roles',
    appRoleById: (id: string) => `/rbac/app/roles/${id}`,
    userAccess: (userId: string) => `/rbac/app/users/${userId}/access`,
    appUserRoles: (userId: string) => `/rbac/app/users/${userId}/roles`,
    appUserOverrides: (userId: string) => `/rbac/app/users/${userId}/overrides`,
    orgPermissions: (organizationId: string) => `/rbac/org/${organizationId}/permissions`,
    orgRoles: (organizationId: string) => `/rbac/org/${organizationId}/roles`,
    orgRoleById: (organizationId: string, id: string) => `/rbac/org/${organizationId}/roles/${id}`,
    orgUserAccess: (organizationId: string, userId: string) => `/rbac/org/${organizationId}/users/${userId}/access`,
    orgUserRoles: (organizationId: string, userId: string) => `/rbac/org/${organizationId}/users/${userId}/roles`,
    orgUserOverrides: (organizationId: string, userId: string) => `/rbac/org/${organizationId}/users/${userId}/overrides`,
  },
  taskforce: {
    dashboard: '/cases',
    complaints: '/cases',
    complaintById: (id: string) => `/cases/${id}`,
    assignComplaint: (id: string) => `/cases/${id}/status`,
    escalateComplaint: (id: string) => `/cases/${id}/escalate`,
    convertComplaintToCase: () => '/cases',
    cases: '/cases',
    caseById: (id: string) => `/cases/${id}`,
    caseStatus: (id: string) => `/cases/${id}/status`,
    caseRoom: (id: string) => `/cases/${id}/room`,
    caseRoomMessages: (roomId: string) => `/case-rooms/${roomId}/messages`,
    assignCase: (id: string) => `/cases/${id}/status`,
    escalateCase: (id: string) => `/cases/${id}/escalate`,
  },
  governance: {
    auditEvents: '/audit/events',
    oversight: '/cases',
  },
  provider: {
    patientSearch: '/profile/search',
    patientProfileByNin: (nin: string) => `/profile/by-nin/${nin}`,
    encountersByNin: (nin: string) => `/encounters/${nin}`,
    encounterById: (id: string) => `/encounters/id/${id}`,
    createEncounterByNin: (nin: string) => `/encounters/${nin}`,
    updateEncounterById: (id: string) => `/encounters/id/${id}`,
    finalizeEncounterById: (id: string) => `/encounters/id/${id}/finalize`,
    labsByNin: (nin: string) => `/labs/${nin}/results`,
    labById: (id: string) => `/labs/results/id/${id}`,
    createLabByNin: (nin: string) => `/labs/${nin}/results`,
    updateLabById: (id: string) => `/labs/results/id/${id}`,
    completeLabById: (id: string) => `/labs/results/id/${id}/complete`,
    pharmacyByNin: (nin: string) => `/pharmacy/${nin}/dispenses`,
    pharmacyById: (id: string) => `/pharmacy/dispenses/id/${id}`,
    createPharmacyByNin: (nin: string) => `/pharmacy/${nin}/dispenses`,
    updatePharmacyById: (id: string) => `/pharmacy/dispenses/id/${id}`,
    dispensePharmacyById: (id: string) => `/pharmacy/dispenses/id/${id}/dispense`,
  },
};
