const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

test('openapi spec contains organization and membership routes', () => {
  const openapiPath = path.resolve(__dirname, '../../../../docs/openapi.json');
  const spec = JSON.parse(fs.readFileSync(openapiPath, 'utf8'));
  const paths = spec.paths || {};

  assert.ok(paths['/orgs']);
  assert.ok(paths['/orgs'].post);
  assert.ok(paths['/orgs'].get);
  assert.ok(paths['/orgs/{orgId}']);
  assert.ok(paths['/orgs/{orgId}'].get);
  assert.ok(paths['/orgs/{orgId}/assign-owner']);
  assert.ok(paths['/orgs/{orgId}/assign-owner'].post);
  assert.ok(paths['/orgs/{orgId}/branches']);
  assert.ok(paths['/orgs/{orgId}/branches'].post);
  assert.ok(paths['/orgs/{orgId}/branches'].get);
  assert.ok(paths['/orgs/{orgId}/branches/{branchId}']);
  assert.ok(paths['/orgs/{orgId}/branches/{branchId}'].get);
  assert.ok(paths['/orgs/{orgId}/branches/{branchId}'].patch);
  assert.ok(paths['/orgs/{orgId}/branches/{branchId}'].delete);
  assert.ok(paths['/orgs/{orgId}/members']);
  assert.ok(paths['/orgs/{orgId}/members'].post);
  assert.ok(paths['/orgs/{orgId}/members'].get);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}']);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}'].get);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}'].patch);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/status']);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/status'].patch);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/branches']);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/branches'].post);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/branches/{assignmentId}']);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/branches/{assignmentId}'].patch);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/branches/{assignmentId}'].delete);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/transfer']);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/transfer'].post);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/history']);
  assert.ok(paths['/orgs/{orgId}/members/{memberId}/history'].get);
  assert.ok(paths['/orgs/{orgId}/memberships/invite']);
  assert.ok(paths['/orgs/{orgId}/memberships/invite'].post);
  assert.ok(paths['/orgs/{orgId}/memberships/{membershipId}/branches']);
  assert.ok(paths['/orgs/{orgId}/memberships/{membershipId}/branches'].post);
  assert.ok(paths['/orgs/{orgId}/memberships/{membershipId}/branches/{branchId}']);
  assert.ok(paths['/orgs/{orgId}/memberships/{membershipId}/branches/{branchId}'].patch);
  assert.ok(paths['/orgs/{orgId}/memberships']);
  assert.ok(paths['/orgs/{orgId}/memberships'].get);
  assert.ok(paths['/orgs/{orgId}/memberships/{membershipId}']);
  assert.ok(paths['/orgs/{orgId}/memberships/{membershipId}'].get);
  assert.ok(paths['/users/{userId}/memberships']);
  assert.ok(paths['/users/{userId}/memberships'].get);
  assert.ok(paths['/users/{userId}/movement-history']);
  assert.ok(paths['/users/{userId}/movement-history'].get);
});
